### ISSUE TITLE
Create Custom hook and context for reference and projects

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/scripture-resources-rcl#23]
DoD: ?

**Comment by birchamp** [comment]
@elsylambert can you add timings?

**Comment by elsylambert** [comment]
Name of the book - Start of the book 1:1-Time taken to Load PSV when scrolling down to the very end- Time Taken when moved to next page-
Mathew - 4 sec- 40 sec- 5 sec
Acts- -4 sec- 48 sec- 5 sec
Rev- 3 sec- 27 sec- 3 sec
Gen- 2 sec- 8 sec - 1 sec
Isa- 2 sec- 10 sec- 1 sec
Psa- 2 sec- 13 sec- 1 sec

**Comment by mandolyte** [comment]
@klappy @RoyalSix Here are my thoughts on teasing out Projects and References from Resources. Please correct as needed!

# Teasing out contexts: resources, projects, and references

## Resources Context

The resources context already exists and essentially represents an entire repo
either the master branch or a tagged release branch.

It is able to see and access any file in a repo, including non-project files.

In particular, it includes the manifest in full. Of interest here is the list
of projects in the manifest.

Here are some snippet examples:
- A portion of a bible resource (ULT):
```yaml
projects:

  -
    title: 'Genesis'
    versification: 'ufw'
    identifier: 'gen'
    sort: 1
    path: './01-GEN.usfm'
    categories: [ 'bible-ot'  ]

  -
    title: 'Exodus'
    versification: 'ufw'
    identifier: 'exo'
    sort: 2
    path: './02-EXO.usfm'
    categories: [ 'bible-ot'  ]
```

- the projects for a non-bible resource (UTW)
```yaml
projects:
  -
    categories:
    identifier: 'bible'
    path: './bible'
    sort: 0
    title: 'unfoldingWord® Translation Words'
    versification:
```

In a bible resource, the "path" attribute is to an actual file for the project,
namely a book of the bible.

In a non-bible resource, the "path" attribute indicates the folder where
the project content may be found.

In summary, a resource represents an entire repo, has access to all the files
in the repo, including the manifest.

## Projects Context

Given that a resource context has access to an entire repo, a project context
might be viewed as a filter or subset of the resource with several additional
features:

- Provides an iterator thru all the projects
- Provides the metadata for for each project
- Provides access to the file content for each project
- Will automatically convert any project file to a format suitable for 
electronic processing, namely:
    - for TSV, convert to a 2d array
    - for USFM, convert to JSON
    - for Markdown, conversion to an in-memory UTF8 string
- Once converted the file content is held until some event forces it to be
reloaded. Example of some events:
    - The parent resource is updated
    - The content is edited and saved
- For bible resources (USFM format in original), the content will be 
optionally accessible by chapter or by chapter and verse.

In summary, a project provides specialized access to the content of a repo 
that is part of the project.

## References Context

Given that a project context has access to all the project files for a 
resource, and can provide specialized services for the project data, then
a reference context might be viewed as a filter or subset of a project 
that is based on a bible resource. These resources are finite: ULT, UST, UTN,
and the original languages (Greek and Hebrew) -- five in all.

A reference consists of three properties: 
- the bookId: such as "gen", "exo" (see above)
- [optional] the chapter: an integer
- [optional] the verse: an integer

A reference consists of specialized functions that access the required
subset of data from a parent project context.

In addition it will be able to extract the underlying text from the JSON
so that it can be used to populate a UI.
